```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=TRUE, comment='', results='markup')

```
# Como usar este livro

Para facilitar uso deste livro cada capítulo foi dividido em cinco partes:  

1. __Script:__ comandos necessários para realizar uma determinada análise  

2. __Explicação:__ breve descrição teórica da análise  

3. __Exemplos:__ alguns exemplos para elucidar o uso da análise com dados reais ou simulados

4. __Gráficos:__ comandos para representar os resultados graficamente  

5. __Diagnóstico:__ comandos para avaliar as premissas e/ou a robustez dos resultados  

***

No final do livro inclui um capítulo com uma breve introdução aos comandos essenciais do R para manipulação de dados e tabelas. 

Em caso de dúvida, abra uma novo [issue](https://github.com/paternogbc/Rguia/issues) no github e deixe um comentário indicando o capítulo e a seção do livro que você não entendeu. Para sugerir modificações ou erros nos comandos entre em contato, ou abra um novo [pull request](https://github.com/paternogbc/Rguia/pulls) com suas modificações.

***